In [1]:
import requests
import nba_api
import pandas as pd
import numpy as np
from datetime import date
from nba_api.stats.endpoints import playbyplayv2,playbyplay, leaguehustlestatsplayer,leaguedashptstats
import time

In [2]:
#last game is 1080
def get_games_range(start_game,end_game):
    start_game_str='00'+str(start_game)
    games_nums=list(range(start_game+1,end_game+1))
    games_strings=['00'+str(x) for x in games_nums]
    df=playbyplayv2.PlayByPlayV2(end_period=6,start_period=1,game_id=start_game_str).play_by_play.get_data_frame()
    for game in games_strings:
        new=playbyplayv2.PlayByPlayV2(end_period=6,start_period=1,game_id=game).play_by_play.get_data_frame()
        print(game)
        df=df.append(new)
        time.sleep(1)
    df.drop(columns=['VIDEO_AVAILABLE_FLAG','PLAYER3_TEAM_NICKNAME','PLAYER3_TEAM_CITY','PLAYER3_TEAM_ID','PLAYER2_TEAM_NICKNAME','PLAYER2_TEAM_CITY','PLAYER2_TEAM_ID','PLAYER1_TEAM_NICKNAME','PLAYER1_TEAM_CITY','PLAYER1_TEAM_ID','PERSON1TYPE','PERSON2TYPE','PERSON3TYPE'])
    return df

In [3]:
def get_specific_games(games_list):
    games_strings=['00'+str(x) for x in games_list]
    df=pd.DataFrame()
    for game in games_strings:
        new=playbyplayv2.PlayByPlayV2(end_period=6,start_period=1,game_id=game).play_by_play.get_data_frame()
        print(game)
        df=df.append(new)
        time.sleep(1)
    df.drop(columns=['VIDEO_AVAILABLE_FLAG','PLAYER3_TEAM_NICKNAME','PLAYER3_TEAM_CITY','PLAYER3_TEAM_ID','PLAYER2_TEAM_NICKNAME','PLAYER2_TEAM_CITY','PLAYER2_TEAM_ID','PLAYER1_TEAM_NICKNAME','PLAYER1_TEAM_CITY','PLAYER1_TEAM_ID','PERSON1TYPE','PERSON2TYPE','PERSON3TYPE'])
    return df

In [4]:
#pbp2021_1=get_games_range(22000001,22000400)
#pbp2021_2=get_games_range(22000401,22000800)
#pbp2021_3=get_games_range(22000801,22001060)
#pbp2021_all=pbp2021_1.append(pbp2021_2).append(pbp2021_3)
#pbp2021_all.to_csv(path_or_buf="PBP Data/2020-21_pbp.csv",index=False)

In [5]:
pbp2021=pd.read_csv(filepath_or_buffer="PBP Data/2020-21_pbp.csv")
games_not_in_yet=list(set(pbp2021.GAME_ID.unique()).symmetric_difference(set(range(22000001,22001081))))
games_to_add=get_specific_games(games_not_in_yet)
pbp2021=pbp2021.append(games_to_add)
pbp2021.to_csv(path_or_buf="PBP Data/2020-21_pbp.csv",index=False)

0022001066
0022001067
0022001068
0022001069
0022001070
0022001071
0022001072
0022001073
0022001074
0022001075
0022001076
0022001077
0022001078
0022001079
0022001080

In [6]:
pbp2021=pd.read_csv(filepath_or_buffer="PBP Data/2020-21_pbp.csv")
pbp2021

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,22000001,2,12,0,1,7:07 PM,12:00,NaN,Start of 1st Period (7:07 PM EST),NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0
1,22000001,4,10,0,1,7:07 PM,12:00,NaN,NaN,NaN,...,Warriors,GSW,2,1610612751,NaN,NaN,NaN,NaN,NaN,1
2,22000001,7,5,45,1,7:07 PM,11:50,Jordan Out of Bounds - Bad Pass Turnover Turno...,NaN,NaN,...,NaN,NaN,1,0,NaN,NaN,NaN,NaN,NaN,1
3,22000001,8,6,2,1,7:07 PM,11:38,Irving S.FOUL (P1.T1) (S.Twardoski),NaN,NaN,...,Warriors,GSW,1,0,NaN,NaN,NaN,NaN,NaN,1
4,22000001,10,3,11,1,7:08 PM,11:38,NaN,NaN,Curry Free Throw 1 of 2 (1 PTS),...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499459,22001080,678,3,12,4,3:28 PM,0:09,Beal Free Throw 2 of 2 (25 PTS),NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
499460,22001080,679,6,1,4,3:29 PM,0:06,Westbrook P.FOUL (P4.T4) (L.Richardson),NaN,NaN,...,Hornets,CHA,1,0,NaN,NaN,NaN,NaN,NaN,1
499461,22001080,681,2,79,4,3:29 PM,0:03,NaN,NaN,MISS Rozier 26' 3PT Pullup Jump Shot,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
499462,22001080,682,4,0,4,3:29 PM,0:03,Smith REBOUND (Off:1 Def:7),NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1
499463,22001080,683,13,0,4,3:29 PM,0:00,NaN,End of 4th Period (3:29 PM EST),NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,1

In [7]:
alley_oops=pbp2021[pbp2021['HOMEDESCRIPTION'].str.contains('Alley',na=False)|
        pbp2021['VISITORDESCRIPTION'].str.contains('Alley',na=False)]
alley_oops

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
262,22000001,373,1,43,3,8:21 PM,11:34,Jordan 1' Alley Oop Layup (2 PTS) (Irving 3 AST),NaN,NaN,...,Nets,BKN,0,0,NaN,NaN,NaN,NaN,NaN,1
284,22000001,401,1,52,3,8:26 PM,10:00,Jordan 1' Alley Oop Dunk (4 PTS) (Durant 2 AST),NaN,NaN,...,Nets,BKN,0,0,NaN,NaN,NaN,NaN,NaN,1
485,22000001,691,1,52,4,9:13 PM,3:13,NaN,NaN,Wiseman 2' Alley Oop Dunk (17 PTS) (Poole 2 AST),...,Warriors,GSW,0,0,NaN,NaN,NaN,NaN,NaN,1
2072,22000005,154,1,43,2,12:46 PM,11:49,NaN,NaN,Williamson 4' Alley Oop Layup (6 PTS) (Bledsoe...,...,Pelicans,NOP,0,0,NaN,NaN,NaN,NaN,NaN,1
2087,22000005,177,1,52,2,12:53 PM,9:27,Adebayo 3' Alley Oop Dunk (6 PTS) (Dragic 5 AST),NaN,NaN,...,Heat,MIA,0,0,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497863,22001077,291,1,52,2,10:00 PM,1:35,Jones 1' Alley Oop Dunk (8 PTS) (Hield 6 AST),NaN,NaN,...,Kings,SAC,0,0,NaN,NaN,NaN,NaN,NaN,1
498012,22001077,512,1,106,4,10:54 PM,9:08,Ramsey 1' Running Alley Oop Dunk Shot (10 PTS)...,NaN,NaN,...,Kings,SAC,0,0,NaN,NaN,NaN,NaN,NaN,1
498036,22001077,544,1,43,4,11:01 PM,5:56,NaN,NaN,Favors 3' Alley Oop Layup (10 PTS) (Clarkson 3...,...,Jazz,UTA,0,0,NaN,NaN,NaN,NaN,NaN,1
498416,22001078,425,1,52,3,3:38 PM,0:56,NaN,NaN,Smith 1' Alley Oop Dunk (9 PTS) (Carter 7 AST),...,Suns,PHX,0,0,NaN,NaN,NaN,NaN,NaN,1
499068,22001080,121,1,52,1,1:26 PM,4:04,Gafford 1' Alley Oop Dunk (2 PTS) (Smith 2 AST),NaN,NaN,...,Wizards,WAS,0,0,NaN,NaN,NaN,NaN,NaN,1

In [8]:
alley_oops=alley_oops[~alley_oops.HOMEDESCRIPTION.str.startswith('MISS',na=False) & 
           ~alley_oops.VISITORDESCRIPTION.str.startswith('MISS',na=False)].\
drop(columns=['PLAYER3_ID','PLAYER3_NAME','PLAYER3_TEAM_ABBREVIATION'])

In [9]:
alley_oops=alley_oops[~alley_oops.PLAYER2_NAME.isna()].copy()
alley_oops['p1']=alley_oops[['PLAYER1_NAME','PLAYER2_NAME']].min(axis=1)
alley_oops['p2']=alley_oops[['PLAYER1_NAME','PLAYER2_NAME']].max(axis=1)
alley_oops

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,VIDEO_AVAILABLE_FLAG,p1,p2
262,22000001,373,1,43,3,8:21 PM,11:34,Jordan 1' Alley Oop Layup (2 PTS) (Irving 3 AST),NaN,NaN,...,Brooklyn,Nets,BKN,0,NaN,NaN,NaN,1,DeAndre Jordan,Kyrie Irving
284,22000001,401,1,52,3,8:26 PM,10:00,Jordan 1' Alley Oop Dunk (4 PTS) (Durant 2 AST),NaN,NaN,...,Brooklyn,Nets,BKN,0,NaN,NaN,NaN,1,DeAndre Jordan,Kevin Durant
485,22000001,691,1,52,4,9:13 PM,3:13,NaN,NaN,Wiseman 2' Alley Oop Dunk (17 PTS) (Poole 2 AST),...,Golden State,Warriors,GSW,0,NaN,NaN,NaN,1,James Wiseman,Jordan Poole
2072,22000005,154,1,43,2,12:46 PM,11:49,NaN,NaN,Williamson 4' Alley Oop Layup (6 PTS) (Bledsoe...,...,New Orleans,Pelicans,NOP,0,NaN,NaN,NaN,1,Eric Bledsoe,Zion Williamson
2087,22000005,177,1,52,2,12:53 PM,9:27,Adebayo 3' Alley Oop Dunk (6 PTS) (Dragic 5 AST),NaN,NaN,...,Miami,Heat,MIA,0,NaN,NaN,NaN,1,Bam Adebayo,Goran Dragic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497863,22001077,291,1,52,2,10:00 PM,1:35,Jones 1' Alley Oop Dunk (8 PTS) (Hield 6 AST),NaN,NaN,...,Sacramento,Kings,SAC,0,NaN,NaN,NaN,1,Buddy Hield,Damian Jones
498012,22001077,512,1,106,4,10:54 PM,9:08,Ramsey 1' Running Alley Oop Dunk Shot (10 PTS)...,NaN,NaN,...,Sacramento,Kings,SAC,0,NaN,NaN,NaN,1,Jahmi'us Ramsey,Terence Davis
498036,22001077,544,1,43,4,11:01 PM,5:56,NaN,NaN,Favors 3' Alley Oop Layup (10 PTS) (Clarkson 3...,...,Utah,Jazz,UTA,0,NaN,NaN,NaN,1,Derrick Favors,Jordan Clarkson
498416,22001078,425,1,52,3,3:38 PM,0:56,NaN,NaN,Smith 1' Alley Oop Dunk (9 PTS) (Carter 7 AST),...,Phoenix,Suns,PHX,0,NaN,NaN,NaN,1,Jalen Smith,Jevon Carter
499068,22001080,121,1,52,1,1:26 PM,4:04,Gafford 1' Alley Oop Dunk (2 PTS) (Smith 2 AST),NaN,NaN,...,Washington,Wizards,WAS,0,NaN,NaN,NaN,1,Daniel Gafford,Ish Smith

In [10]:
alley_oops.groupby(['p1','p2']).size().reset_index().rename(columns={0:'count'}).sort_values(by='count',ascending=False).head(10)

                        p1               p2  count
198           Clint Capela       Trae Young     69
688            Mike Conley      Rudy Gobert     39
559           John Collins       Trae Young     32
298         DeAndre Jordan     James Harden     32
313          Deandre Ayton     Devin Booker     31
184             Chris Paul    Deandre Ayton     29
390          Dwight Powell      Luka Doncic     27
281         Darius Garland    Jarrett Allen     26
301         DeAndre Jordan     Kyrie Irving     25
427  Giannis Antetokounmpo  Khris Middleton     22

In [11]:
misses=pbp2021[pbp2021.HOMEDESCRIPTION.str.startswith('MISS',na=False)| 
           pbp2021.VISITORDESCRIPTION.str.startswith('MISS',na=False)]
missed_dunks=misses[misses.HOMEDESCRIPTION.str.contains('Dunk',na=False)|
                   misses.VISITORDESCRIPTION.str.contains('Dunk',na=False)]
blocked_dunks=missed_dunks[missed_dunks.HOMEDESCRIPTION.str.contains('BLOCK',na=False)|
                   missed_dunks.VISITORDESCRIPTION.str.contains('BLOCK',na=False)]
blocked_dunks

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
1546,22000004,79,2,108,1,10:53 PM,6:41,Jones BLOCK (1 BLK),NaN,MISS Powell 1' Cutting Dunk Shot,...,NaN,NaN,4,1627745,Damian Jones,1.610613e+09,Phoenix,Suns,PHX,1
6195,22000013,615,2,7,4,9:17 PM,4:47,Simmons BLOCK (3 BLK),NaN,MISS Bryant 2' Dunk,...,NaN,NaN,4,1627732,Ben Simmons,1.610613e+09,Philadelphia,76ers,PHI,1
8051,22000017,543,2,7,4,9:56 PM,9:25,Allen BLOCK (1 BLK),NaN,MISS Poeltl 1' Dunk,...,NaN,NaN,4,1628960,Grayson Allen,1.610613e+09,Memphis,Grizzlies,MEM,1
9136,22000019,768,2,50,5,11:48 PM,0:00,Barton BLOCK (1 BLK),NaN,MISS Barnes 4' Running Dunk,...,NaN,NaN,4,203115,Will Barton,1.610613e+09,Denver,Nuggets,DEN,1
12669,22000026,709,2,7,4,10:19 PM,0:03,Valentine BLOCK (1 BLK),NaN,MISS Stanley 1' Dunk,...,NaN,NaN,4,1627756,Denzel Valentine,1.610613e+09,Chicago,Bulls,CHI,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493085,22001066,497,2,9,3,8:44 PM,0:05,MISS Mays 2' Driving Dunk,NaN,Oliver BLOCK (2 BLK),...,NaN,NaN,5,1628419,Cameron Oliver,1.610613e+09,Houston,Rockets,HOU,1
493567,22001067,530,2,7,4,8:57 PM,6:23,MISS Claxton 1' Dunk,NaN,Allen BLOCK (1 BLK),...,NaN,NaN,5,1628386,Jarrett Allen,1.610613e+09,Cleveland,Cavaliers,CLE,1
493600,22001067,575,2,52,4,9:05 PM,2:46,Green BLOCK (1 BLK),NaN,MISS Wade 1' Alley Oop Dunk,...,NaN,NaN,4,201145,Jeff Green,1.610613e+09,Brooklyn,Nets,BKN,1
496106,22001073,327,2,9,3,2:30 PM,10:58,MISS Payton 2' Driving Dunk,NaN,Kornet BLOCK (3 BLK),...,NaN,NaN,5,1628436,Luke Kornet,1.610613e+09,Boston,Celtics,BOS,1
496556,22001074,402,2,7,3,10:25 PM,8:30,Brown BLOCK (5 BLK),NaN,MISS Oturu 1' Dunk,...,NaN,NaN,4,1629650,Moses Brown,1.610613e+09,Oklahoma City,Thunder,OKC,1

In [12]:
#as the blockee
blocked_dunks.groupby('PLAYER1_NAME').size().reset_index().rename(columns={0:'count'}).\
sort_values(by='count',ascending=False).head(15)

         PLAYER1_NAME  count
86        Ivica Zubac     12
192       Rudy Gobert      9
15       Bobby Portis      7
90    Jaden McDaniels      7
193     Rui Hachimura      6
231   Zion Williamson      5
176   P.J. Washington      5
174        OG Anunoby      5
18     Brandon Clarke      5
52     Derrick Favors      5
139        Kyle Kuzma      5
183  Precious Achiuwa      5
228    Xavier Tillman      5
110      John Collins      5
102     Jarrett Allen      5

In [13]:
#as the blocker
blocked_dunks.groupby('PLAYER3_NAME').size().reset_index().rename(columns={0:'count'}).\
sort_values(by='count',ascending=False).head(15)

              PLAYER3_NAME  count
139           Nerlens Noel     20
82            Jakob Poeltl     14
89           Jarrett Allen     13
30            Clint Capela     10
113      Kenyon Martin Jr.      9
134            Moses Brown      9
136           Myles Turner      9
160         Richaun Holmes      8
61       Freddie Gillespie      7
18             Brook Lopez      7
94            Jerami Grant      7
138               Naz Reid      7
111        Kelly Oubre Jr.      6
167            Rudy Gobert      6
64   Giannis Antetokounmpo      6

In [14]:
hustle=leaguehustlestatsplayer.LeagueHustleStatsPlayer(
    per_mode_time="PerGame",season="2020-21",
    season_type_all_star="Regular Season").hustle_stats_player.get_data_frame().set_index("PLAYER_ID")
hustle_cleaned=hustle[['PLAYER_NAME','TEAM_ID','TEAM_ABBREVIATION','CONTESTED_SHOTS','DEFLECTIONS','CHARGES_DRAWN',
                      'DEF_LOOSE_BALLS_RECOVERED','DEF_BOXOUTS']]
hustle_cleaned

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,CONTESTED_SHOTS,DEFLECTIONS,CHARGES_DRAWN,DEF_LOOSE_BALLS_RECOVERED,DEF_BOXOUTS
PLAYER_ID,,,,,,,,
203932,Aaron Gordon,1610612743,DEN,3.76,1.02,0.00,0.22,0.18
1628988,Aaron Holiday,1610612754,IND,3.09,1.47,0.00,0.23,0.42
1630174,Aaron Nesmith,1610612738,BOS,2.87,0.52,0.02,0.24,0.39
1627846,Abdel Nader,1610612756,PHX,3.17,0.75,0.00,0.21,0.46
1629690,Adam Mokoka,1610612741,CHI,0.29,0.29,0.00,0.00,0.21
...,...,...,...,...,...,...,...,...
1627812,Yogi Ferrell,1610612746,LAC,1.40,0.80,0.00,0.80,0.00
1629139,Yuta Watanabe,1610612761,TOR,3.90,0.68,0.02,0.22,0.62
203897,Zach LaVine,1610612741,CHI,6.45,1.33,0.00,0.38,0.45
1630192,Zeke Nnaji,1610612743,DEN,2.55,0.52,0.00,0.07,0.50
1629627,Zion Williamson,1610612740,NOP,7.72,1.79,0.02,0.48,0.79

In [15]:
speed_dist=leaguedashptstats.LeagueDashPtStats(
    last_n_games=0,month=0,opponent_team_id=0,per_mode_simple="PerGame",
    player_or_team="Player",pt_measure_type="SpeedDistance",season="2020-21",
    season_type_all_star="Regular Season").league_dash_pt_stats.get_data_frame().set_index("PLAYER_ID")
speed_dist_cleaned=speed_dist[['PLAYER_NAME','TEAM_ID','TEAM_ABBREVIATION','GP','MIN','DIST_MILES_DEF','AVG_SPEED_DEF']]
speed_dist_cleaned

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,MIN,DIST_MILES_DEF,AVG_SPEED_DEF
PLAYER_ID,,,,,,,
203932,Aaron Gordon,1610612743,DEN,49,27.99,0.90,3.71
1628988,Aaron Holiday,1610612754,IND,66,17.82,0.66,3.98
1630174,Aaron Nesmith,1610612738,BOS,45,14.43,0.54,4.15
1627846,Abdel Nader,1610612756,PHX,24,14.80,0.53,4.10
1629690,Adam Mokoka,1610612741,CHI,14,4.01,0.15,3.99
...,...,...,...,...,...,...,...
1627812,Yogi Ferrell,1610612746,LAC,9,12.23,0.42,3.89
1629139,Yuta Watanabe,1610612761,TOR,50,14.46,0.54,4.19
203897,Zach LaVine,1610612741,CHI,58,35.06,1.22,3.93
1630192,Zeke Nnaji,1610612743,DEN,41,9.36,0.34,4.12
1629627,Zion Williamson,1610612740,NOP,61,33.21,1.20,4.00

In [16]:
#defensive_stats=leaguedashptstats.LeagueDashPtStats(
#    last_n_games=0,month=0,opponent_team_id=0,per_mode_simple="PerGame",
#    player_or_team="Player",pt_measure_type="Defense",season="2020-21",
#    season_type_all_star="Regular Season").league_dash_pt_stats.get_data_frame().set_index("PLAYER_ID")
#defensive_stats_cleaned=defensive_stats[['PLAYER_NAME','TEAM_ID','TEAM_ABBREVIATION','GP','STL','BLK','DREB']]
#defensive_stats_cleaned

In [17]:
#traditional defensive stats approximate by tracking (deflections ~ steals, contested shots ~ blocks, def reb ~ boxouts)
cols_to_use = hustle_cleaned.columns.difference(speed_dist_cleaned.columns)
joined = speed_dist_cleaned.merge(hustle_cleaned[cols_to_use], left_index=True, right_index=True, how='left')
# cols_to_use = defensive_stats_cleaned.columns.difference(joined.columns)
# joined = joined.merge(defensive_stats_cleaned[cols_to_use], left_index=True, right_index=True, how='left')
joined_min_gp=joined[(joined.GP>36)].copy() #for minimums
joined_min_gp

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,MIN,DIST_MILES_DEF,AVG_SPEED_DEF,CHARGES_DRAWN,CONTESTED_SHOTS,DEFLECTIONS,DEF_BOXOUTS,DEF_LOOSE_BALLS_RECOVERED
PLAYER_ID,,,,,,,,,,,,
203932,Aaron Gordon,1610612743,DEN,49,27.99,0.90,3.71,0.00,3.76,1.02,0.18,0.22
1628988,Aaron Holiday,1610612754,IND,66,17.82,0.66,3.98,0.00,3.09,1.47,0.42,0.23
1630174,Aaron Nesmith,1610612738,BOS,45,14.43,0.54,4.15,0.02,2.87,0.52,0.39,0.24
202692,Alec Burks,1610612752,NYK,48,25.61,0.87,3.95,0.00,4.84,1.43,0.10,0.31
1630197,Aleksej Pokusevski,1610612760,OKC,44,23.84,0.82,3.87,0.00,6.71,0.80,0.24,0.11
...,...,...,...,...,...,...,...,...,...,...,...,...
1630214,Xavier Tillman,1610612763,MEM,58,18.66,0.68,4.02,0.00,7.42,1.29,2.20,0.19
1629139,Yuta Watanabe,1610612761,TOR,50,14.46,0.54,4.19,0.02,3.90,0.68,0.62,0.22
203897,Zach LaVine,1610612741,CHI,58,35.06,1.22,3.93,0.00,6.45,1.33,0.45,0.38
1630192,Zeke Nnaji,1610612743,DEN,41,9.36,0.34,4.12,0.00,2.55,0.52,0.50,0.07
1629627,Zion Williamson,1610612740,NOP,61,33.21,1.20,4.00,0.02,7.72,1.79,0.79,0.48

In [18]:
per_36_percent_ranks=joined_min_gp[['CHARGES_DRAWN', 'CONTESTED_SHOTS', 'DEFLECTIONS', 
               'DEF_BOXOUTS','DEF_LOOSE_BALLS_RECOVERED']].\
div(joined_min_gp.MIN,axis=0).multiply(36,axis=0).apply(lambda x: x.rank(pct=True)).add_suffix("_pct_rank")
per_36_percent_ranks["sum"]=per_36_percent_ranks.sum(axis=1)
per_36_percent_ranks

,CHARGES_DRAWN_pct_rank,CONTESTED_SHOTS_pct_rank,DEFLECTIONS_pct_rank,DEF_BOXOUTS_pct_rank,DEF_LOOSE_BALLS_RECOVERED_pct_rank,sum
PLAYER_ID,,,,,,
203932,0.153392,0.138643,0.144543,0.073746,0.147493,0.657817
1628988,0.153392,0.365782,0.861357,0.498525,0.616519,2.495575
1630174,0.536873,0.525074,0.132743,0.572271,0.876106,2.643068
202692,0.153392,0.469027,0.516224,0.014749,0.545723,1.699115
1630197,0.153392,0.761062,0.095870,0.185841,0.011799,1.207965
...,...,...,...,...,...,...
1630214,0.153392,0.926254,0.710914,0.991150,0.324484,3.106195
1629139,0.533923,0.737463,0.318584,0.707965,0.814159,3.112094
203897,0.153392,0.448378,0.168142,0.265487,0.404130,1.439528
1630192,0.153392,0.749263,0.510324,0.764012,0.132743,2.309735
1629627,0.365782,0.663717,0.486726,0.507375,0.752212,2.775811

In [19]:
joined_min_gp=joined_min_gp.merge(per_36_percent_ranks,how='left',left_index=True,right_index=True)

In [20]:
#joined_min_gp.sort_values(['sum']).to_csv(path_or_buf='trick_yall_running_around.csv')
joined_min_gp.sort_values(['sum']).head(20)

,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,MIN,DIST_MILES_DEF,AVG_SPEED_DEF,CHARGES_DRAWN,CONTESTED_SHOTS,DEFLECTIONS,DEF_BOXOUTS,DEF_LOOSE_BALLS_RECOVERED,CHARGES_DRAWN_pct_rank,CONTESTED_SHOTS_pct_rank,DEFLECTIONS_pct_rank,DEF_BOXOUTS_pct_rank,DEF_LOOSE_BALLS_RECOVERED_pct_rank,sum
PLAYER_ID,,,,,,,,,,,,,,,,,,
203932,Aaron Gordon,1610612743,DEN,49,27.99,0.90,3.71,0.00,3.76,1.02,0.18,0.22,0.153392,0.138643,0.144543,0.073746,0.147493,0.657817
1628422,Damyean Dotson,1610612739,CLE,45,19.53,0.64,3.89,0.00,2.39,0.59,0.22,0.15,0.153392,0.088496,0.064897,0.215339,0.138643,0.660767
1628370,Malik Monk,1610612766,CHA,41,21.28,0.71,3.73,0.00,2.50,0.79,0.14,0.19,0.153392,0.070796,0.156342,0.079646,0.221239,0.681416
1627854,Bryn Forbes,1610612749,MIL,70,19.35,0.69,3.88,0.00,2.01,0.54,0.30,0.16,0.153392,0.044248,0.056047,0.336283,0.174041,0.764012
1629022,Lonnie Walker IV,1610612759,SAS,59,25.33,0.85,3.93,0.02,3.65,1.18,0.13,0.17,0.410029,0.206490,0.306785,0.038348,0.082596,1.044248
201961,Wayne Ellington,1610612765,DET,46,22.00,0.69,3.82,0.00,3.37,0.67,0.13,0.26,0.153392,0.277286,0.067847,0.056047,0.519174,1.073746
1629744,Matt Thomas,1610612762,UTA,44,7.36,0.27,4.18,0.00,1.02,0.20,0.18,0.07,0.153392,0.156342,0.044248,0.533923,0.262537,1.150442
1628420,Monte Morris,1610612743,DEN,46,25.62,0.84,3.75,0.02,3.60,0.98,0.21,0.26,0.407080,0.174041,0.176991,0.109145,0.315634,1.182891
1630197,Aleksej Pokusevski,1610612760,OKC,44,23.84,0.82,3.87,0.00,6.71,0.80,0.24,0.11,0.153392,0.761062,0.095870,0.185841,0.011799,1.207965
202694,Marcus Morris Sr.,1610612746,LAC,57,26.35,0.86,3.69,0.00,3.68,1.02,1.07,0.12,0.153392,0.165192,0.188791,0.693215,0.008850,1.209440
1629164,Brandon Goodwin,1610612737,ATL,47,13.18,0.45,4.03,0.00,2.00,0.53,0.26,0.11,0.153392,0.265487,0.212389,0.427729,0.179941,1.238938
1629630,Ja Morant,1610612763,MEM,62,32.50,1.09,3.76,0.03,3.65,1.27,0.49,0.30,0.442478,0.058997,0.197640,0.315634,0.241888,1.256637
1629014,Anfernee Simons,1610612757,POR,63,17.18,0.59,4.08,0.03,2.86,0.61,0.11,0.14,0.598820,0.321534,0.117994,0.070796,0.168142,1.277286
1629012,Collin Sexton,1610612739,CLE,59,35.51,1.13,3.67,0.03,4.20,1.78,0.17,0.38,0.427729,0.073746,0.383481,0.029499,0.389381,1.303835
1629599,Amir Coffey,1610612746,LAC,44,8.97,0.30,3.88,0.00,1.25,0.39,0.18,0.09,0.153392,0.159292,0.253687,0.439528,0.297935,1.303835
203926,Doug McDermott,1610612754,IND,65,24.41,0.92,4.11,0.03,3.74,0.44,0.58,0.15,0.489676,0.280236,0.008850,0.504425,0.061947,1.345133
1628379,Luke Kennard,1610612746,LAC,62,19.39,0.65,3.88,0.02,2.94,0.67,0.44,0.11,0.463127,0.262537,0.106195,0.474926,0.044248,1.351032
204060,Joe Ingles,1610612762,UTA,66,27.82,0.92,3.74,0.01,3.00,1.24,0.73,0.22,0.327434,0.047198,0.283186,0.557522,0.153392,1.368732
203552,Seth Curry,1610612755,PHI,57,28.74,0.94,3.76,0.05,2.58,1.42,0.30,0.25,0.595870,0.020649,0.371681,0.194690,0.203540,1.386431
1630177,Theo Maledon,1610612760,OKC,64,27.57,0.94,3.90,0.00,4.85,1.32,0.25,0.29,0.153392,0.389381,0.342183,0.141593,0.368732,1.395280